name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        working-directory: pirr_app
        run: flutter pub get

      - name: Analyze
        working-directory: pirr_app
        run: flutter analyze

      - name: Run tests
        working-directory: pirr_app
        run: flutter test


