name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get
        working-directory: pirr_app

      - name: Analyze code
        run: flutter analyze
        working-directory: pirr_app

      - name: Run tests
        run: flutter test
        working-directory: pirr_app

      - name: Build release APK
        run: flutter build apk --release
        working-directory: pirr_app

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: pirr-mini-apk
          path: pirr_app/build/app/outputs/flutter-apk/app-release.apk

